// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: record.proto
// Protobuf C++ Version: 6.33.0

#ifndef record_2eproto_2epb_2eh
#define record_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 6033000
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_record_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_record_2eproto {
  static const ::uint32_t offsets[];
};
extern "C" {
extern const ::google::protobuf::internal::DescriptorTable descriptor_table_record_2eproto;
}  // extern "C"
class Record;
struct RecordDefaultTypeInternal;
extern RecordDefaultTypeInternal _Record_default_instance_;
extern const ::google::protobuf::internal::ClassDataFull Record_class_data_;
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google


// ===================================================================


// -------------------------------------------------------------------

class Record final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:Record) */ {
 public:
  inline Record() : Record(nullptr) {}
  ~Record() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Record* PROTOBUF_NONNULL msg, ::std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Record));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Record(::google::protobuf::internal::ConstantInitialized);

  inline Record(const Record& from) : Record(nullptr, from) {}
  inline Record(Record&& from) noexcept
      : Record(nullptr, ::std::move(from)) {}
  inline Record& operator=(const Record& from) {
    CopyFrom(from);
    return *this;
  }
  inline Record& operator=(Record&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* PROTOBUF_NONNULL mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* PROTOBUF_NONNULL GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* PROTOBUF_NONNULL GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Record& default_instance() {
    return *reinterpret_cast<const Record*>(
        &_Record_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Record& a, Record& b) { a.Swap(&b); }
  inline void Swap(Record* PROTOBUF_NONNULL other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Record* PROTOBUF_NONNULL other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Record* PROTOBUF_NONNULL New(::google::protobuf::Arena* PROTOBUF_NULLABLE arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Record>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Record& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Record& from) { Record::MergeImpl(*this, from); }

  private:
  static void MergeImpl(::google::protobuf::MessageLite& to_msg,
                        const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return IsInitializedImpl(*this);
  }

  private:
  static bool IsInitializedImpl(const MessageLite& msg);

  public:
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      const ::google::protobuf::MessageLite& msg, ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* PROTOBUF_NONNULL _InternalSerialize(
      ::uint8_t* PROTOBUF_NONNULL target,
      ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Record* PROTOBUF_NONNULL other);
 private:
  template <typename T>
  friend ::absl::string_view(::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "Record"; }

  explicit Record(::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  Record(::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Record& from);
  Record(
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, Record&& from) noexcept
      : Record(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL GetClassData() const PROTOBUF_FINAL;
  static void* PROTOBUF_NONNULL PlacementNew_(
      const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
      ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
  static constexpr auto InternalNewImpl_();

 public:
  static constexpr auto InternalGenerateClassData_();

  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kLegalAdressFieldNumber = 2,
    kCompanyNameFieldNumber = 3,
    kFoundationYearFieldNumber = 1,
    kOccupationFieldNumber = 4,
    kForeignEconomicActivityFieldNumber = 5,
  };
  // required string legalAdress = 2;
  bool has_legaladress() const;
  void clear_legaladress() ;
  const ::std::string& legaladress() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_legaladress(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_legaladress();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_legaladress();
  void set_allocated_legaladress(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_legaladress() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_legaladress(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_legaladress();

  public:
  // required string CompanyName = 3;
  bool has_companyname() const;
  void clear_companyname() ;
  const ::std::string& companyname() const;
  template <typename Arg_ = const ::std::string&, typename... Args_>
  void set_companyname(Arg_&& arg, Args_... args);
  ::std::string* PROTOBUF_NONNULL mutable_companyname();
  [[nodiscard]] ::std::string* PROTOBUF_NULLABLE release_companyname();
  void set_allocated_companyname(::std::string* PROTOBUF_NULLABLE value);

  private:
  const ::std::string& _internal_companyname() const;
  PROTOBUF_ALWAYS_INLINE void _internal_set_companyname(const ::std::string& value);
  ::std::string* PROTOBUF_NONNULL _internal_mutable_companyname();

  public:
  // required int32 foundationYear = 1;
  bool has_foundationyear() const;
  void clear_foundationyear() ;
  ::int32_t foundationyear() const;
  void set_foundationyear(::int32_t value);

  private:
  ::int32_t _internal_foundationyear() const;
  void _internal_set_foundationyear(::int32_t value);

  public:
  // optional int32 occupation = 4;
  bool has_occupation() const;
  void clear_occupation() ;
  ::int32_t occupation() const;
  void set_occupation(::int32_t value);

  private:
  ::int32_t _internal_occupation() const;
  void _internal_set_occupation(::int32_t value);

  public:
  // optional int32 foreignEconomicActivity = 5;
  bool has_foreigneconomicactivity() const;
  void clear_foreigneconomicactivity() ;
  ::int32_t foreigneconomicactivity() const;
  void set_foreigneconomicactivity(::int32_t value);

  private:
  ::int32_t _internal_foreigneconomicactivity() const;
  void _internal_set_foreigneconomicactivity(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:Record)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 5,
                                   0, 0,
                                   2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena);
    inline explicit Impl_(
        ::google::protobuf::internal::InternalVisibility visibility,
        ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
        const Record& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr legaladress_;
    ::google::protobuf::internal::ArenaStringPtr companyname_;
    ::int32_t foundationyear_;
    ::int32_t occupation_;
    ::int32_t foreigneconomicactivity_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_record_2eproto;
};

extern const ::google::protobuf::internal::ClassDataFull Record_class_data_;

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Record

// required int32 foundationYear = 1;
inline bool Record::has_foundationyear() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000004U);
  return value;
}
inline void Record::clear_foundationyear() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.foundationyear_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000004U);
}
inline ::int32_t Record::foundationyear() const {
  // @@protoc_insertion_point(field_get:Record.foundationYear)
  return _internal_foundationyear();
}
inline void Record::set_foundationyear(::int32_t value) {
  _internal_set_foundationyear(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000004U);
  // @@protoc_insertion_point(field_set:Record.foundationYear)
}
inline ::int32_t Record::_internal_foundationyear() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.foundationyear_;
}
inline void Record::_internal_set_foundationyear(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.foundationyear_ = value;
}

// required string legalAdress = 2;
inline bool Record::has_legaladress() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000001U);
  return value;
}
inline void Record::clear_legaladress() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.legaladress_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000001U);
}
inline const ::std::string& Record::legaladress() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Record.legalAdress)
  return _internal_legaladress();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Record::set_legaladress(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  _impl_.legaladress_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Record.legalAdress)
}
inline ::std::string* PROTOBUF_NONNULL Record::mutable_legaladress()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  ::std::string* _s = _internal_mutable_legaladress();
  // @@protoc_insertion_point(field_mutable:Record.legalAdress)
  return _s;
}
inline const ::std::string& Record::_internal_legaladress() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.legaladress_.Get();
}
inline void Record::_internal_set_legaladress(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.legaladress_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Record::_internal_mutable_legaladress() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.legaladress_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Record::release_legaladress() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Record.legalAdress)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000001U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  auto* released = _impl_.legaladress_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.legaladress_.Set("", GetArena());
  }
  return released;
}
inline void Record::set_allocated_legaladress(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000001U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
  }
  _impl_.legaladress_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.legaladress_.IsDefault()) {
    _impl_.legaladress_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Record.legalAdress)
}

// required string CompanyName = 3;
inline bool Record::has_companyname() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000002U);
  return value;
}
inline void Record::clear_companyname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.companyname_.ClearToEmpty();
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000002U);
}
inline const ::std::string& Record::companyname() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:Record.CompanyName)
  return _internal_companyname();
}
template <typename Arg_, typename... Args_>
PROTOBUF_ALWAYS_INLINE void Record::set_companyname(Arg_&& arg, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  _impl_.companyname_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:Record.CompanyName)
}
inline ::std::string* PROTOBUF_NONNULL Record::mutable_companyname()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  ::std::string* _s = _internal_mutable_companyname();
  // @@protoc_insertion_point(field_mutable:Record.CompanyName)
  return _s;
}
inline const ::std::string& Record::_internal_companyname() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.companyname_.Get();
}
inline void Record::_internal_set_companyname(const ::std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.companyname_.Set(value, GetArena());
}
inline ::std::string* PROTOBUF_NONNULL Record::_internal_mutable_companyname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.companyname_.Mutable( GetArena());
}
inline ::std::string* PROTOBUF_NULLABLE Record::release_companyname() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:Record.CompanyName)
  if (!CheckHasBit(_impl_._has_bits_[0], 0x00000002U)) {
    return nullptr;
  }
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  auto* released = _impl_.companyname_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.companyname_.Set("", GetArena());
  }
  return released;
}
inline void Record::set_allocated_companyname(::std::string* PROTOBUF_NULLABLE value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    SetHasBit(_impl_._has_bits_[0], 0x00000002U);
  } else {
    ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
  }
  _impl_.companyname_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.companyname_.IsDefault()) {
    _impl_.companyname_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:Record.CompanyName)
}

// optional int32 occupation = 4;
inline bool Record::has_occupation() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000008U);
  return value;
}
inline void Record::clear_occupation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.occupation_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000008U);
}
inline ::int32_t Record::occupation() const {
  // @@protoc_insertion_point(field_get:Record.occupation)
  return _internal_occupation();
}
inline void Record::set_occupation(::int32_t value) {
  _internal_set_occupation(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000008U);
  // @@protoc_insertion_point(field_set:Record.occupation)
}
inline ::int32_t Record::_internal_occupation() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.occupation_;
}
inline void Record::_internal_set_occupation(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.occupation_ = value;
}

// optional int32 foreignEconomicActivity = 5;
inline bool Record::has_foreigneconomicactivity() const {
  bool value = CheckHasBit(_impl_._has_bits_[0], 0x00000010U);
  return value;
}
inline void Record::clear_foreigneconomicactivity() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.foreigneconomicactivity_ = 0;
  ClearHasBit(_impl_._has_bits_[0],
                  0x00000010U);
}
inline ::int32_t Record::foreigneconomicactivity() const {
  // @@protoc_insertion_point(field_get:Record.foreignEconomicActivity)
  return _internal_foreigneconomicactivity();
}
inline void Record::set_foreigneconomicactivity(::int32_t value) {
  _internal_set_foreigneconomicactivity(value);
  SetHasBit(_impl_._has_bits_[0], 0x00000010U);
  // @@protoc_insertion_point(field_set:Record.foreignEconomicActivity)
}
inline ::int32_t Record::_internal_foreigneconomicactivity() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.foreigneconomicactivity_;
}
inline void Record::_internal_set_foreigneconomicactivity(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.foreigneconomicactivity_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // record_2eproto_2epb_2eh
